#!/bin/zsh

# +------+
# | ruby |
# +------+

eval "$(rbenv init -)"

# +------------+
# | frameworks |
# +------------+

source $ZSH/oh-my-zsh.sh

# +---------+
# | aliases |
# +---------+

source $HOME/aliases

# +------------+
# | completion |
# +------------+

autoload -Uz compinit
compinit
_comp_options+=(globdots)

# +------------+
# | navigation |
# +------------+

setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

# +--------------+
# | fuzzy search |
# +--------------+

source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

# +---------+
# | vi mode |
# +---------+

bindkey -v
export KEYTIMEOUT=1

zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# +--------+
# | cursor |
# +--------+

cursor_mode() {
    # See https://ttssh2.osdn.jp/manual/4/en/usage/tips/vim.html for cursor shapes
    cursor_block='\e[2 q'
    cursor_beam='\e[6 q'

    function zle-keymap-select {
        if [[ ${KEYMAP} == vicmd ]] ||
            [[ $1 = 'block' ]]; then
            echo -ne $cursor_block
        elif [[ ${KEYMAP} == main ]] ||
            [[ ${KEYMAP} == viins ]] ||
            [[ ${KEYMAP} = '' ]] ||
            [[ $1 = 'beam' ]]; then
            echo -ne $cursor_beam
        fi
    }

    zle-line-init() {
        echo -ne $cursor_beam
    }

    zle -N zle-keymap-select
    zle -N zle-line-init
}

cursor_mode

# +----------------+
# | start X Server |
# +----------------+

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi
